service: klambda-service
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  fibonacci:
    handler: fibonacci/fibonacci.handler
    description: fibonacci of number
    events:
      - http:
          path: fibonacci/{number}
          method: get
  print:
    handler: print/print.handler
    events:
      - http: 
          path: print
          method: post
          